### ISSUE TITLE
Tests Failed

### ISSUE THREAD

**Issue by gvaibhavraj2** [pixos/poptrie#22]
The lookup Full Route and lookup full route update fails for tests both for ipv4 and ipv6.

**Comment by drpnd** [comment]
I ran tests on three platforms (see the following) to check your issue, but they passed all the tests.

Tested platforms:
- FreeBSD 9.3 on x86-64 VM with gcc 4.2.1
- Up-to-date OS X on Mid 2014 platform with Apple's clang
- Ubuntu server 15.10 with gcc 5.3.1 on Intel Core i3-6100

Can you provide the following information to track the issue?
- Console log of make test command
- OS and compiler information

**Comment by gvaibhavraj2** [comment]
@drpnd I ran the basic.c file in tests folder and got this output.
![screen shot 2016-06-02 at 9 21 09 pm](https://cloud.githubusercontent.com/assets/7159037/15751536/122e197e-2908-11e6-80d8-5f7d404cf89a.png)

**Comment by drpnd** [comment]
Ah, I figure it out.  You just need to run your a.out at the parent directory.  The test program is designed to be launched from Makefile (which should be generated by automake/autoconf and configure script) at the top directory, and it contains some hard-coded file names of routing tables for the tests.  Therefore, it fails when it is run at different directories.

**Comment by drpnd** [comment]
WFM
